import { CoffeeType } from './coffee.model';

export const db: CoffeeType[] = [
  {
    id: 1,
    name: 'Капучино',
    subTitle: 'с шоколадом',
    type: 'cappuccino',
    price: 270,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee1.png',
    description: 'Кофе с натуральные чёрным шоколадом для тех, кому хочется послаще',
    rating: 4.5,
  },
  {
    id: 2,
    name: 'Капучино',
    subTitle: 'с гранатом',
    type: 'cappuccino',
    price: 280,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee3.png',
    description: 'Необычное сочетание граната и кофе предаёт этому напитку пряные нотки.',
    rating: 4.9,
  },
  {
    id: 3,
    name: 'Капучино',
    subTitle: 'с ванилью',
    type: 'cappuccino',
    price: 250,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee2.png',
    description: 'Нежное капучино с добавлением ванили. Мягкий вкус и отличное настроение на весь день.',
    rating: 4.7,
  },
  {
    id: 4,
    name: 'Капучино',
    subTitle: 'с персиком',
    type: 'cappuccino',
    price: 250,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee4.png',
    description: 'Нежное капучино с добавлением ароматного персика. Отличный выбор для любителей фруктовых нот в кофе.',
    rating: 4.2,
  },
  {
    id: 5,
    name: 'Латте',
    subTitle: 'с ванилью',
    type: 'latte',
    price: 220,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee2.png',
    description: 'Насладитесь нежным латте с нотками ванили. Идеальное сочетание молока и эспрессо для сладкого опыта.',
    rating: 4.5,
  },
  {
    id: 6,
    name: 'Макиатто',
    subTitle: 'с карамелью',
    type: 'macchiato',
    price: 200,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee1.png',
    description: 'Классический макиатто, украшенный сладкой карамелью. Наслаждайтесь простотой и насыщенным вкусом.',
    rating: 4,
  },
  {
    id: 7,
    name: 'Американо',
    subTitle: 'с ментоловым сиропом',
    type: 'americano',
    price: 180,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee3.png',
    description: 'Освежающий американо с добавлением ментолового сиропа. Идеальный выбор для ценителей свежести.',
    rating: 4.3,
  },
  {
    id: 8,
    name: 'Латте',
    subTitle: 'с кленовым сиропом',
    type: 'latte',
    price: 240,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee4.png',
    description:
      'Изысканное латте с добавлением ароматного кленового сиропа. Нежное сочетание молока и эспрессо с легкой сладостью.',
    rating: 4.3,
  },
  {
    id: 9,
    name: 'Макиатто',
    subTitle: 'с шоколадом',
    type: 'macchiato',
    price: 210,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee2.png',
    description: 'Ароматный макиатто с нотами шоколада. Превосходное сочетание эспрессо и сладкого шоколадного вкуса.',
    rating: 4.2,
  },
  {
    id: 10,
    name: 'Макиатто',
    subTitle: 'с миндальным вкусом',
    type: 'macchiato',
    price: 210,
    image: 'https://cdn-bucket.hb.ru-msk.vkcs.cloud/purple-images/coffee-api/coffee1.png',
    description: 'Ароматный макиатто с нежным миндальным вкусом. Идеальное сочетание эспрессо с легкой ореховой нотой.',
    rating: 4.4,
  },
];
